apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: k8-service
  labels:
    app: k8-service
spec:
  replicas: 3
  selector:
    matchLabels:
      task: nginx
  template:
    metadata:
      labels:
        task: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 81
